apiVersion: apps/v1
kind: Deployment
metadata:
  name: registrationapi-deployment
spec:
  selector:
    matchLabels:
      app: registrationserviceapi-pod
  template:
    metadata:
      labels:
        app: registrationserviceapi-pod
    spec:
      containers:
      - name: registrationserviceapi-container
        image: ipascontreg.azurecr.io/registrationserviceapi:v5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 30001
        - containerPort: 30021